spring:
  application:
    name: infra
  profiles:
    include:
      - common
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
custom:
  jwt:
    secret: ${JWT_SECRET}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    prefix: ${JWT_TOKEN_PREFIX}
    header: ${JWT_HEADER_STRING}

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
