spring:
  application:
    name: infra
  profiles:
    include:
      - common
custom:
  jwt:
    secret: ${JWT_SECRET}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    prefix: ${JWT_TOKEN_PREFIX}
    header: ${JWT_HEADER_STRING}

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
