spring:
  application:
    name: domain
  profiles:
    include:
      - infra
      - common

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
