server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api
  profiles:
    include:
      - domain
      - infra
      - common

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
